"""Inference script for cube detection model."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path
from typing import Any

import torch
from PIL import Image

# Add parent directory to path for imports
SRC_DIR = Path(__file__).resolve().parents[1]
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from cube_detection.dataset import REGRESSION_TARGET_KEYS, build_inference_transform
from cube_detection.model import build_resnet18_regressor


class CubeDetectionInference:
    """Inference wrapper for cube visibility regression."""

    def __init__(self, checkpoint_path: str | Path, device: str = "cuda" if torch.cuda.is_available() else "cpu"):
        """
        Initialize the inference model.

        Args:
            checkpoint_path: Path to the model checkpoint (.pt file)
            device: Device to run inference on ("cuda" or "cpu")
        """
        self.checkpoint_path = Path(checkpoint_path)
        self.device = torch.device(device)

        if not self.checkpoint_path.exists():
            raise FileNotFoundError(f"Checkpoint not found: {self.checkpoint_path}")

        checkpoint = torch.load(self.checkpoint_path, map_location=self.device)

        # Extract configuration from checkpoint (with safe defaults for older checkpoints)
        self.image_size = int(checkpoint.get("image_size", 224))
        self.target_key = str(checkpoint.get("target_key", "visible_image_ratio"))
        self.bounded_output = bool(checkpoint.get("bounded_output", True))
        self.visibility_threshold = float(checkpoint.get("visibility_threshold", 0.01))

        if self.target_key not in REGRESSION_TARGET_KEYS:
            raise ValueError(
                f"Unsupported target_key in checkpoint: {self.target_key!r}. "
                f"Expected one of {REGRESSION_TARGET_KEYS}."
            )

        self.model = build_resnet18_regressor(
            pretrained=False,
            freeze_backbone=False,
            bounded_output=self.bounded_output,
        )
        self.model.load_state_dict(checkpoint["model_state_dict"])
        self.model.to(self.device)
        self.model.eval()
        self.preprocess = build_inference_transform(image_size=self.image_size, augment=False)

        checkpoint_sha = _file_sha256_hex(self.checkpoint_path)
        print(f"[OrpheusDebug] checkpoint={self.checkpoint_path} checkpoint_sha256={checkpoint_sha}")
        print(f"Model loaded from: {self.checkpoint_path}")
        print(f"  Device: {self.device}")
        print(f"  Image size: {self.image_size}")
        print(f"  Target key: {self.target_key}")
        print(f"  Bounded output: {self.bounded_output}")
        print(f"  Visibility threshold: {self.visibility_threshold}")

    def _load_and_preprocess_image(self, image_path: str | Path) -> torch.Tensor:
        """
        Load and preprocess an image.

        Args:
            image_path: Path to the image file

        Returns:
            Preprocessed tensor of shape (3, image_size, image_size)
        """
        image_path = Path(image_path)
        if not image_path.exists():
            raise FileNotFoundError(f"Image not found: {image_path}")

        with Image.open(image_path) as image:
            return self.preprocess(image)

    @staticmethod
    def _parse_labels_from_filename(image_path: str | Path) -> dict[str, Any]:
        """
        Parse optional encoded labels from filenames generated by data_generator.

        Example suffixes:
        __label_cube_visible__vis_0.123456__infrm_0.654321__edge_-0.100000
        """
        stem = Path(image_path).stem
        parsed: dict[str, Any] = {}

        for token in stem.split("__"):
            if "_" not in token:
                continue
            key, raw_value = token.split("_", 1)

            if key == "label":
                parsed["label"] = raw_value
            elif key == "vis":
                try:
                    parsed["visible_image_ratio"] = float(raw_value)
                except ValueError:
                    pass
            elif key == "infrm":
                try:
                    parsed["inframe_fraction"] = float(raw_value)
                except ValueError:
                    pass
            elif key == "edge":
                try:
                    parsed["edge_margin"] = float(raw_value)
                except ValueError:
                    pass

        return parsed

    @torch.no_grad()
    def infer(self, image_path: str | Path) -> dict[str, Any]:
        """
        Run inference for a single image.

        Args:
            image_path: Path to image

        Returns:
            Result dictionary with raw prediction and convenience fields.
        """
        image_tensor = self._load_and_preprocess_image(image_path)
        image_tensor = image_tensor.unsqueeze(0).to(self.device)

        image_sha = _file_sha256_hex(Path(image_path))
        print(f"[OrpheusDebug] image_path={Path(image_path)} image_sha256={image_sha}")
        print(
            "[OrpheusDebug] image_tensor "
            f"shape={tuple(image_tensor.shape)} "
            f"min={float(image_tensor.min().item()):.6f} "
            f"max={float(image_tensor.max().item()):.6f} "
            f"mean={float(image_tensor.mean().item()):.6f}"
        )

        prediction_tensor = self.model(image_tensor)
        prediction_value = float(prediction_tensor.squeeze().detach().cpu().item())

        result: dict[str, Any] = {
            "raw_prediction": prediction_value,
            self.target_key: prediction_value,
            "is_cube_visible": bool(prediction_value >= self.visibility_threshold),
            "visibility_threshold": self.visibility_threshold,
            "image_path": str(Path(image_path)),
        }

        parsed_labels = self._parse_labels_from_filename(image_path)
        if parsed_labels:
            result["parsed_filename_labels"] = parsed_labels
            if self.target_key in parsed_labels:
                gt = float(parsed_labels[self.target_key])
                result["parsed_target_value"] = gt
                result["abs_error_vs_filename_target"] = abs(prediction_value - gt)

        print(f"[OrpheusDebug] raw_prediction={prediction_value:.6f}")
        print(f"[OrpheusDebug] is_cube_visible={result['is_cube_visible']}")

        return result

    def infer_batch(self, image_paths: list[str | Path]) -> list[dict[str, Any]]:
        """Run inference on multiple images."""
        return [self.infer(image_path) for image_path in image_paths]


# ============================================================================
# INFERENCE CONFIGURATION - MODIFY THESE VARIABLES
# ============================================================================

# Path to the checkpoint (.pt file)
CHECKPOINT_PATH = r"D:\OneDrive - Venusnet\Dokumente\4. Robot V2\Orpheus (RobotAI)\runs\cube_detection\20260411-121406\checkpoints\best.pt"

# Path to the image for inference
IMAGE_PATH = r"C:\Users\nicow\Downloads\detection_image.jpg"

# Device: "cuda" or "cpu"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ============================================================================


def _file_sha256_hex(path: Path) -> str:
    try:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            while True:
                chunk = handle.read(1024 * 1024)
                if not chunk:
                    break
                digest.update(chunk)
        return digest.hexdigest()
    except Exception:
        return "unavailable"


def main() -> None:
    """Main inference function."""
    inference = CubeDetectionInference(checkpoint_path=CHECKPOINT_PATH, device=DEVICE)

    print("\n--- Running Inference ---")
    print(f"Image: {IMAGE_PATH}")
    result = inference.infer(image_path=IMAGE_PATH)

    print("\n--- Prediction Results ---")
    print(f"raw_prediction: {result['raw_prediction']:.6f}")
    print(f"{inference.target_key}: {result[inference.target_key]:.6f}")
    print(f"is_cube_visible: {result['is_cube_visible']} (threshold={result['visibility_threshold']:.6f})")

    if "parsed_filename_labels" in result:
        print(f"parsed_filename_labels: {result['parsed_filename_labels']}")
    if "parsed_target_value" in result:
        print(f"parsed_target_value: {result['parsed_target_value']:.6f}")
    if "abs_error_vs_filename_target" in result:
        print(f"abs_error_vs_filename_target: {result['abs_error_vs_filename_target']:.6f}")


if __name__ == "__main__":
    main()
